/** Datos mock locales; más adelante sustituir por API. */

import { addDaysIso } from '../../utils/adminFilters';

/** Día “hoy” del mock (admin Resumen = citas con esta fecha). */
export const MOCK_HOY = '2026-03-19';

/** Fin de la ventana de 14 días para la vista barbero (inclusive). */
export const MOCK_AGENDA_2SEM_FIN = addDaysIso(MOCK_HOY, 13);

export const INITIAL_BARBEROS = [
  { id: 1, nombre: 'Kevin Barbero', porcentaje: 50, cortesRealizados: 45 },
  { id: 2, nombre: 'Luis Master', porcentaje: 40, cortesRealizados: 60 },
  { id: 3, nombre: 'Andrés Fade', porcentaje: 60, cortesRealizados: 30 },
];

export const INITIAL_GASTOS = [
  { id: 1, concepto: 'Alquiler Local', monto: 1200.0, categoria: 'Fijo', fecha: '2026-03-01' },
  { id: 2, concepto: 'Publicidad Facebook', monto: 150.0, categoria: 'Marketing', fecha: '2026-03-10' },
  { id: 3, concepto: 'Suministros', monto: 89.5, categoria: 'Operativo', fecha: '2026-02-15' },
];

export const INITIAL_CLIENTES = [
  {
    id: 1,
    nombre: 'Jorge Villanueva',
    rango: 'Plata',
    cortes: 8,
    proximos: 10,
    notas: 'Prefiere fade bajo',
  },
  {
    id: 2,
    nombre: 'Carlos Mendez',
    rango: 'Oro',
    cortes: 15,
    proximos: 20,
    notas: '',
  },
  {
    id: 3,
    nombre: 'Miguel Torres',
    rango: 'Bronce',
    cortes: 2,
    proximos: 5,
    notas: 'Alergia a ciertos productos',
  },
];

export const INITIAL_SERVICIOS = [
  { id: 1, nombre: 'Corte Fade VIP', precio: 25.0, duracion: 45, activo: true },
  { id: 2, nombre: 'Arreglo de Barba', precio: 15.0, duracion: 30, activo: true },
  { id: 3, nombre: 'Limpieza Facial', precio: 20.0, duracion: 25, activo: true },
];

function acita(p) {
  return { notas: '', estado: 'Pendiente', ...p };
}

const H = MOCK_HOY;
const D = (n) => addDaysIso(MOCK_HOY, n);

/** Todas las citas programadas en mock (varias fechas). El admin “hoy” filtra por MOCK_HOY. */
export const CITAS_AGENDA_COMPLETA = [
  acita({
    id: 1,
    fecha: H,
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Fade bien bajo en patillas y nuca, sin línea dura. Degradé suave.',
    hora: '10:30 AM',
    monto: 25.0,
  }),
  acita({
    id: 2,
    fecha: H,
    clienteId: 2,
    barberoId: 2,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Luis Master',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Barba corta tipo corporate, bigote recortado y perfilado de patillas.',
    hora: '11:15 AM',
    monto: 15.0,
    notas: 'Cliente VIP',
  }),
  acita({
    id: 3,
    fecha: H,
    clienteId: 3,
    barberoId: 1,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Limpieza Facial',
    pedidoCliente: 'Limpieza facial express; piel sensible, sin fragancias fuertes.',
    hora: '03:45 PM',
    monto: 20.0,
  }),
  acita({
    id: 4,
    fecha: D(1),
    clienteId: 2,
    barberoId: 1,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Solo perfilar contorno y cejas, barba con 5 mm de largo.',
    hora: '09:00 AM',
    monto: 15.0,
  }),
  acita({
    id: 5,
    fecha: D(1),
    clienteId: 3,
    barberoId: 1,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Mismo estilo que la última vez: degrado medio, parte lateral peinada.',
    hora: '02:00 PM',
    monto: 25.0,
  }),
  acita({
    id: 6,
    fecha: D(2),
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Limpieza Facial',
    pedidoCliente: 'Tratamiento completo + vapor; comentó sequedad en frente.',
    hora: '11:00 AM',
    monto: 20.0,
  }),
  acita({
    id: 7,
    fecha: D(4),
    clienteId: 3,
    barberoId: 1,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Quiere llevar el flequillo un poco más largo que siempre.',
    hora: '04:30 PM',
    monto: 25.0,
  }),
  acita({
    id: 8,
    fecha: D(7),
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Solo contorno y cejas; barba de 3 días, natural.',
    hora: '10:00 AM',
    monto: 15.0,
  }),
  acita({
    id: 9,
    fecha: D(7),
    clienteId: 2,
    barberoId: 1,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Fade alto, caja en la parte superior, rayita limpia.',
    hora: '05:00 PM',
    monto: 25.0,
  }),
  acita({
    id: 10,
    fecha: D(10),
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Corte antes de evento; pide acabado mate en cera.',
    hora: '12:00 PM',
    monto: 25.0,
  }),
  acita({
    id: 11,
    fecha: D(13),
    clienteId: 3,
    barberoId: 1,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Limpieza Facial',
    pedidoCliente: 'Solo zona T; alergia a ciertos productos (ver notas internas si aplica).',
    hora: '03:00 PM',
    monto: 20.0,
  }),
  acita({
    id: 12,
    fecha: D(2),
    clienteId: 1,
    barberoId: 2,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Luis Master',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Degradé bajo tipo burst fade, patillas en punta.',
    hora: '10:30 AM',
    monto: 25.0,
  }),
  acita({
    id: 13,
    fecha: D(3),
    clienteId: 3,
    barberoId: 2,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Luis Master',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Barba candado corto, líneas definidas en mejillas.',
    hora: '01:15 PM',
    monto: 15.0,
  }),
  acita({
    id: 14,
    fecha: D(5),
    clienteId: 2,
    barberoId: 2,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Luis Master',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Mantener largo arriba para peinar hacia atrás.',
    hora: '09:30 AM',
    monto: 25.0,
  }),
  acita({
    id: 15,
    fecha: D(8),
    clienteId: 1,
    barberoId: 2,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Luis Master',
    servicio: 'Limpieza Facial',
    pedidoCliente: 'Primera vez; pidió explicación breve de cada paso.',
    hora: '11:45 AM',
    monto: 20.0,
  }),
  acita({
    id: 16,
    fecha: D(12),
    clienteId: 2,
    barberoId: 2,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Luis Master',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Perfilado de bigote y simetría; barba media.',
    hora: '04:00 PM',
    monto: 15.0,
  }),
  acita({
    id: 17,
    fecha: D(2),
    clienteId: 2,
    barberoId: 3,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Andrés Fade',
    servicio: 'Limpieza Facial',
    pedidoCliente: 'Enfocado en poros y puntos negros en nariz.',
    hora: '02:30 PM',
    monto: 20.0,
  }),
  acita({
    id: 18,
    fecha: D(6),
    clienteId: 3,
    barberoId: 3,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Andrés Fade',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Drop fade, transición suave detrás de oreja.',
    hora: '10:00 AM',
    monto: 25.0,
  }),
  acita({
    id: 19,
    fecha: D(11),
    clienteId: 1,
    barberoId: 3,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Andrés Fade',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Llevar orejas descubiertas, cabello texturizado arriba.',
    hora: '03:30 PM',
    monto: 25.0,
  }),
];

/** Solo citas del día mock “hoy” (panel admin Resumen). */
export const INITIAL_CITAS = CITAS_AGENDA_COMPLETA.filter((c) => c.fecha === MOCK_HOY);

/** Citas pasadas (historial) — mock. */
export const INITIAL_HISTORIAL_CITAS = [
  {
    id: 101,
    fecha: '2026-03-08',
    hora: '09:00 AM',
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Fade bajo, acabado natural.',
    estado: 'Completada',
    monto: 25.0,
  },
  {
    id: 102,
    fecha: '2026-03-07',
    hora: '04:00 PM',
    clienteId: 3,
    barberoId: 3,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Andrés Fade',
    servicio: 'Corte Fade VIP',
    pedidoCliente: 'Corte + peinado con volumen.',
    estado: 'Completada',
    monto: 25.0,
  },
  {
    id: 103,
    fecha: '2026-03-05',
    hora: '02:30 PM',
    clienteId: 2,
    barberoId: 2,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Luis Master',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Perfilado completo; canceló antes del servicio.',
    estado: 'Cancelada',
    monto: 0,
  },
  {
    id: 104,
    fecha: '2026-03-12',
    hora: '11:00 AM',
    clienteId: 2,
    barberoId: 1,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Arreglo de Barba',
    pedidoCliente: 'Perfilado clásico.',
    estado: 'Completada',
    monto: 15.0,
  },
  {
    id: 105,
    fecha: '2026-03-14',
    hora: '02:00 PM',
    clienteId: 1,
    barberoId: 1,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Corte Fade VIP',
    estado: 'Completada',
    monto: 25.0,
  },
  {
    id: 106,
    fecha: '2026-02-28',
    hora: '10:00 AM',
    clienteId: 3,
    barberoId: 1,
    clienteNombre: 'Miguel Torres',
    barberoNombre: 'Kevin Barbero',
    servicio: 'Limpieza Facial',
    estado: 'Completada',
    monto: 20.0,
  },
  {
    id: 107,
    fecha: '2026-03-10',
    hora: '09:30 AM',
    clienteId: 1,
    barberoId: 2,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Luis Master',
    servicio: 'Corte Fade VIP',
    estado: 'Completada',
    monto: 25.0,
  },
  {
    id: 108,
    fecha: '2026-03-09',
    hora: '04:00 PM',
    clienteId: 2,
    barberoId: 2,
    clienteNombre: 'Carlos Mendez',
    barberoNombre: 'Luis Master',
    servicio: 'Arreglo de Barba',
    estado: 'Completada',
    monto: 15.0,
  },
  {
    id: 109,
    fecha: '2026-03-06',
    hora: '12:30 PM',
    clienteId: 1,
    barberoId: 3,
    clienteNombre: 'Jorge Villanueva',
    barberoNombre: 'Andrés Fade',
    servicio: 'Corte Fade VIP',
    estado: 'Completada',
    monto: 25.0,
  },
];

export const INITIAL_INVENTARIO = [
  { id: 1, nombre: 'Cera Mate Texturizante', precio: 15.0, stock: 2, stockMinimo: 3 },
  { id: 2, nombre: 'Tónico Capilar Crecimiento', precio: 25.5, stock: 1, stockMinimo: 2 },
  { id: 3, nombre: 'Afeitadora de Precisión', precio: 12.0, stock: 5, stockMinimo: 2 },
];

/** Inventario privado por barbero (mock). El salón usa INITIAL_INVENTARIO. */
export const INITIAL_INVENTARIO_BARBERO = [
  { id: 201, barberoId: 1, nombre: 'Cuchillas safety (caja)', stock: 8, stockMinimo: 3 },
  { id: 202, barberoId: 1, nombre: 'Spray mesa hidroalcohólico', stock: 1, stockMinimo: 2 },
  { id: 203, barberoId: 1, nombre: 'Cera bolsillo', stock: 2, stockMinimo: 1 },
  { id: 204, barberoId: 2, nombre: 'Aceite pre-afeitado', stock: 4, stockMinimo: 2 },
  { id: 205, barberoId: 2, nombre: 'Toallas desechables', stock: 12, stockMinimo: 10 },
  { id: 206, barberoId: 3, nombre: 'Peines carbono', stock: 3, stockMinimo: 2 },
  { id: 207, barberoId: 3, nombre: 'Biberón aceite barba', stock: 0, stockMinimo: 1 },
];

export const INITIAL_STATS = {
  ingresosTotales: 15450.0,
  cortesMesActual: 120,
};

/** Mock mes anterior para comparativas en resumen. */
export const STATS_MES_ANTERIOR_MOCK = {
  ingresosTotales: 13820.0,
  cortesMesActual: 105,
};

export const CHART_DAY_REVENUE_USD = [1180, 1420, 980, 2050, 1680, 2320, 2510];
